# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0002_auto_20171122_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
