-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 19:02:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MyFullFriends
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MyFullFriends
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyFullFriends` DEFAULT CHARACTER SET utf8 ;
USE `MyFullFriends` ;

-- -----------------------------------------------------
-- Table `MyFullFriends`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyFullFriends`.`friends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `friend_since` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyFullFriends`.`relationships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyFullFriends`.`relationships` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `friends_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_relationships_friends_idx` (`user_id` ASC),
  INDEX `fk_relationships_friends1_idx` (`friends_id` ASC),
  CONSTRAINT `fk_relationships_friends`
    FOREIGN KEY (`user_id`)
    REFERENCES `MyFullFriends`.`friends` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relationships_friends1`
    FOREIGN KEY (`friends_id`)
    REFERENCES `MyFullFriends`.`friends` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT friends(name, age, friend_since, year, created_at, updated_at)
VALUES("Jonah Ramirez",2,"September 9th",2015,NOW(),NOW());

SELECT * FROM friends;