# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 17:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_auto_20171122_1635'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='friend',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
